// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package google

import (
	"practice_godi/batch"
	"practice_godi/service"
)

// Injectors from wire.go:

func InitializeTask() batch.Task {
	sampleService := service.NewService()
	task := batch.NewTask(sampleService)
	return task
}
